cargo-features = ["edition"]

[package]
name = "devilution-comparer"
version = "0.2.1"
authors = ["Dennis Duda <git@seri.tools>"]
edition = '2018'

[dependencies]
zydis = "0.0.3"
notify = "4"
clap = "2"
regex = "1"
num-traits = "0.2"
